-- TEST DBCR - UATX1
-- DISABLE TRIGGERS
ALTER TRIGGER ABMS.OH_PERS_REDETER_CREATE_TRG DISABLE;
ALTER TRIGGER ABMS.OH_PERS_REDETER_UPDATE_TRG DISABLE;
ALTER TRIGGER ABMS.OH_PERS_REDETER_HST_TRG DISABLE;
ALTER TRIGGER ABMS.OH_PERS_REDETER_ID_TRG DISABLE;
-- DBCR 1 PERS_REDETER
MERGE INTO ABMS.OH_PERS_REDETER TGT
USING (
SELECT DISTINCT *
	FROM (
		SELECT
		R.ID,
		R.PGM_PERS_ID,
		ROW_NUMBER() OVER(PARTITION BY PGM_PERS_ID ORDER BY BEG_DATE DESC) RANK,
		created_on as NEW_COMPL_DATE,
		R.BEG_DATE,
		R.DUE_DATE
		FROM ABMS.OH_PERS_REDETER R
		WHERE
		R.CREATED_BY = '2012565'
		AND R.PGM_PERS_ID = '23400610'
	) ORDERED_REDUE
	WHERE RANK > 1
) SRC
ON TGT.ID = SRC.ID
WHEN MATCHED THEN UPDATE
SET
	TGT.COMPL_DATE = SRC.NEW_COMPL_DATE,
	TGT.COMPL_RSN_CODE = 'NV',
	TGT.UPDATE_BY = '2012565',
	TGT.UPDATED_ON = SYSDATE
WHERE
	CREATED_BY = '2012565';
COMMIT;
-- ENABLE TRIGGERS
ALTER TRIGGER ABMS.OH_PERS_REDETER_CREATE_TRG ENABLE;
ALTER TRIGGER ABMS.OH_PERS_REDETER_UPDATE_TRG ENABLE;
ALTER TRIGGER ABMS.OH_PERS_REDETER_HST_TRG ENABLE;
ALTER TRIGGER ABMS.OH_PERS_REDETER_ID_TRG ENABLE;
-- DISABLE TRIGGERS
ALTER TRIGGER ABMS.REDETERUP_TRG DISABLE;
ALTER TRIGGER ABMS.OH_REDETER_HST_TRG DISABLE;
ALTER TRIGGER ABMS.REDETER_TRG DISABLE;
ALTER TRIGGER ABMS.REDETERIN_TRG DISABLE;
-- DBCR 2 REDETER
MERGE INTO ABMS.REDETER TGT 
USING (
	SELECT DISTINCT *
	FROM (
		SELECT
		ROW_NUMBER() OVER(PARTITION BY PGM_ID ORDER BY BEG_DATE DESC) RANK,
		created_on as NEW_COMPL_DATE,
		R.*
		FROM ABMS.REDETER R
		WHERE
		R.CREATED_BY = '2012565'
		AND R.PGM_ID = '14709703'
	) ORDERED_REDUE
	WHERE RANK > 1
) SRC
WHEN MATCHED THEN UPDATE
SET
	TGT.COMPL_DATE = SRC.NEW_COMPL_DATE,
	TGT.COMPL_RSN_CODE = 'NV',
	TGT.UPDATE_BY = '2012565',
	TGT.UPDATED_ON = SYSDATE
WHERE
	CREATED_BY = '2012565';
COMMIT;
-- ENABLE TRIGGERS
ALTER TRIGGER ABMS.REDETERUP_TRG ENABLE;
ALTER TRIGGER ABMS.OH_REDETER_HST_TRG ENABLE;
ALTER TRIGGER ABMS.REDETER_TRG ENABLE;
ALTER TRIGGER ABMS.REDETERIN_TRG ENABLE;