name: Super-Linter

on: push

jobs:
  super-lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run Super-Linter
        uses: github/super-linter@v7
        env:
          DEFAULT_BRANCH: main
          token: ${{ secrets.isk_token }}
